name: home_gym
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  equatable: ^1.0.0
  meta: ^1.1.8
  flutter_fling: 
    path: C:\Users\sagre\Desktop\flutter_fling-master\flutter_fling-master
  path_provider: ^1.6.11
  json_annotation: ^3.0.1
  provider: ^4.3.1
  image_picker: ^0.6.7+4  
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  firebase_core: "^0.5.0"
  firebase_auth: "^0.18.0+1"
  firebase_auth_ui: ^1.0.1
  video_compress: ^2.0.0
  flare_splash_screen: ^3.0.1
  confetti: ^0.5.4+1
  giffy_dialog: ^1.8.0
  intro_views_flutter: '^2.8.1'
  data_connection_checker: ^0.3.4
  timeline_tile: ^0.1.2
  google_fonts: ^1.1.0
  webview_flutter: ^0.3.22+1
  get_ip: ^0.4.0
  http_server: ^0.9.8+3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  json_serializable: ^3.3.0
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  analyzer: '0.39.14'
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/videos/
     - assets/flares/
     - public/index.html
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
